version: '3'
services:
  keyserver:
    #image: mmmaxwwwell/keyserver
    build:
      context: ./keyserver/
      dockerfile: ./Dockerfile
    container_name: keyserver
    restart: always
    env_file:
      - ./settings/keyserver.env
    networks:
      - keyserver-db
      - keyserver
    ports: 
     - "8888:8888"
  mongo:
    image: mongo:bionic
    container_name: mongo
    restart: always
    volumes:
      - ./appdata/mongo/data/db:/data/db
      - ./appdata/mongo/data/log:/data/log
      - ./settings/mongod.conf:/etc/mongod.conf
    networks:
      - keyserver-db
    # ports: 
    #   - "27017:27017"
    command: mongod --config /etc/mongod.conf

networks:
  keyserver-db:
  keyserver: