#!/bin/bash
[[ -d settings ]] || cp -r settings.example settings

mkdir -p ./appdata/nginx
[[ -d ./appdata/nginx/dhparam.pem ]] || openssl dhparam -out ./appdata/nginx/dhparam.pem 4096

if [ -d "./settings" ] 
then
    echo "It looks like the settings folder already exists."
    echo "Do you want to overwrite the existing passwords? [y/N]"
    read -i N -e OVERWRITE
else
    OVERWRITE=y
fi

if [ "$OVERWRITE" == "y" ]; then
    echo "Enter the mongo admin username"
    read MONGODB_ADMIN_USER

    echo "Enter the mongo admin password:"
    read -s MONGODB_ADMIN_PASS
    echo "Enter the mongo admin password again:"
    read -s MONGODB_ADMIN_PASS2
    if [ "$MONGODB_ADMIN_PASS" != "$MONGODB_ADMIN_PASS2" ]; then
        echo "password mismatch, retry"
        exit
    fi

    echo "Enter the keyserver mongo username"
    read KEYSERVER_MONGODB_USER

    echo "Enter the keyserver mongo password:"
    read -s KEYSERVER_MONGODB_PASS
    echo "Enter the keyserver mongo password again:"
    read -s KEYSERVER_MONGODB_PASS2
    if [ "$KEYSERVER_MONGODB_PASS" != "$KEYSERVER_MONGODB_PASS2" ]; then
        echo "password mismatch, retry"
        exit
    fi

    sed -i '/MONGODB_ADMIN_USER/d' ./settings/mongo.env > /dev/null
    sed -i '/MONGODB_ADMIN_PASS/d' ./settings/mongo.env > /dev/null
    sed -i '/KEYSERVER_MONGODB_USER/d' ./settings/mongo.env > /dev/null
    sed -i '/KEYSERVER_MONGODB_PASS/d' ./settings/mongo.env > /dev/null

    echo "MONGODB_ADMIN_USER=$MONGODB_ADMIN_USER" >> ./settings/mongo.env
    echo "MONGODB_ADMIN_PASS=$MONGODB_ADMIN_PASS" >> ./settings/mongo.env
    echo "KEYSERVER_MONGODB_USER=$KEYSERVER_MONGODB_USER" >> ./settings/mongo.env
    echo "KEYSERVER_MONGODB_PASS=$KEYSERVER_MONGODB_PASS" >> ./settings/mongo.env
fi

echo "Do you want to load the passwords into mongo? [y/N]"
read -i N -e RELOAD

if [ "$RELOAD" == "y" ]; then
    echo "Setting up mongo admin and keyserver user..."
    cd bootstrap
    ./bootstrap
    cd ..
fi

#copy temp certs
source ./settings/common.env
sudo docker run --rm -it -v ${PWD##*/}_certbot-etc:/certbot-etc -v $(pwd)/staging-certs:/staging-certs bash /usr/local/bin/bash -c " mkdir -p /certbot-etc/live/$HOSTED_URL;cp /staging-certs/* /certbot-etc/live/$HOSTED_URL"

echo "Setup complete"